### PR TITLE
Add back the sidebar on safety regions and municipality level

### PR DESCRIPTION
**Pull request by VWSCoronaDashboard14**
No data props were given to the sidebar hence why it wasn't showing.

### CODE REVIEW

**Review by VWSCoronaDashboard4 — APPROVED** [review]

**Comment by VWSCoronaDashboard** [comment]
Should data be a required prop for MunicipalityLayout? We could prevent this error with TS.

**Comment by VWSCoronaDashboard8** [comment]
@VWSCoronaDashboard4 @VWSCoronaDashboard yes lets make data a required property for all layouts as part of this PR

**Review by VWSCoronaDashboard8 — APPROVED** [review]
Looks good, but data should be made required to avoid this in the future

**Comment by VWSCoronaDashboard10** [comment]
I've reverted the change which made the data required. Both the `/veiligheidsregio` and `/gemeente` routes don't need data because they don't render a sidebar.
To prevent future errors I've updated the layout props to the following:
```tsx
type MunicipalityLayoutProps = {
  lastGenerated: string;
  children?: React.ReactNode;
} & (
  | {
      data: Municipal;
      municipalityName: string;
    }
  | {
      isLandingPage: true;
      data?: undefined;
      municipalityName?: undefined;
    }
);
```
Which means the component can receive one of these:
1. `data`-prop in combination with `municipalityName`-prop, OR:
2. the `isLandingPage`-prop with value `true` in combination with an undefined `data`- and `municipalityName`-prop.

As you can see I've included the `municipalityName` because that was also left empty, resulting in no municipality name rendered in the sidebar.

All the above also applies for the safety region layout.

**Pull request merged**
