### PR TITLE
feature/COR-1455-remove-topical-page-measure-theme-components

### PR DESCRIPTION
**Pull request by VWSCoronaDashboard26**
## Summary

* removed measure themes section from topical page;
* removed all measure theme component schemas from Sanity;
* updated topical page groq query and query types;
* updated theme schema to mark tiles and other properties as not-required, allowing for 'simple' themes without tiles or links;
* reverted removal of `sizes` export from theme, as this resulted in breaking changes;

### Motivation
I opted to completely remove the measure theme (component) schemas as alter the existing (base) theme schema instead. This means that a base theme can now contain tiles but these are no longer required. This essentially simplifies the workflow within the CMS as can be seen in the attached screenshots.

#### Before
<details>
<summary>Toggle before screenshots</summary>

image

COR-1455_before
</details>

#### After
<details>
<summary>Toggle after screenshots</summary>

image

COR-1455_after
</details>

### CODE REVIEW

**Comment by VWSCoronaDashboard18** [comment]
Screenshot 2023-03-08 at 10 48 07

Would it be nice to remove the icon as well? Or is that out of scope!
Feel free to resolve this nontheless

**Review by VWSCoronaDashboard18 — APPROVED** [review]
Nice adjustment! And great use of the Sanity themes!

**Comment by VWSCoronaDashboard26** [comment]
> Would it be nice to remove the icon as well? Or is that out of scope? Feel free to resolve this nonetheless.

I have thought about this as well, though I think it would be nice to keep this around. The 'tricky' thing about our icons is that they use a name that _implies_ their use case, but that does not necessarily mean that _should_ always be used in that specific use case. As per example, this specific `maatregelen` icon is still being used in the remaining component (see screenshots) and the sidebar.

**Review by VWSCoronaDashboard28 — APPROVED** [review]
Looks good!

**Pull request merged**
