### PR TITLE
COR- 997 - Redirect to vr/gm page instead of topical vr/gm page

### PR DESCRIPTION
**Pull request by VWSCoronaDashboard24**

### CODE REVIEW

**Review by VWSCoronaDashboard18 — APPROVED** [review]
Nice and easy fix

**Review by VWSCoronaDashboard18 — COMMENTED** [review]
Does this also redirects when people deep link the topical GM/VR page?

**Comment by VWSCoronaDashboard24** [comment]
> @VWSCoronaDashboard18 Does this also redirects when people deep link the topical GM/VR page?

Good one, forgot about that. Will make some changes.

**Review by VWSCoronaDashboard18 — APPROVED** [review]
Nice!

**Pull request merged**
